# baseURL: "https://mabbasiazad.github.io/portfolio/" 
baseURL: "https://mabbasiazad.github.io/" 

title: mehdi azad
paginate: 20
theme: PaperMod
# theme: congo

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Posts
          url: posts/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Patents
          url: patents/
          weight: 3
        # - name: Search
        #   url: search/
          weight: 4
        # - name: Courses
        #   url: courses/
          # weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: " "
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: bright
    disableThemeToggle: false
    hideFooter: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mehdi Azad
          subtitle: 
            Hi! I'm Mehdi Azad. I'm a professor at George Brown College in the School of Computer Technology. 
            I hold a master’s degree in Systems Design Engineering from the University of Waterloo 
            and in Mechatronics Engineering form Iran University of Science and Technology. 
            With over 10 years of professional and teaching experience in machine learning, data science, 
            and robotics, I have successfully conducted and led numerous projects in the fields of
            energy, healthcare, and biotechnology.
            # <br />
            # <br />
            # Click [<u>here</u>](cv.pdf) to download my CV. 
            # <br />

          # imageUrl: "my_pic.png"
          imageUrl: "my_pic_formal.jpg"
          imageWidth: 120
          imageHeight: 120
          imageTitle: mehdi image
          buttons:
            - name: Posts
              url: posts/
            - name: Papers
              url: papers/
            - name: Patents
              url: patents/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Search
            #   url: search/
    
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:m32abbas@uwaterloo.ca
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: LinkedIn
          url: https://www.linkedin.com/in/mazadgole/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=KQK75p0AAAAJ&hl=en
        - name: YouTube
          url: https://www.youtube.com/channel/UC3LZuMiLWtLDcC5ufWDgGMg
        - name: GitHub
          url: https://github.com/mabbasiazad
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/Mehdi09953267

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Home"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
